FROM node:18-alpine

ENV NODE_ENV=development

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./

COPY ./@app/server ./@app/server

RUN npm install -g pnpm
RUN pnpm install

EXPOSE 3000

ENTRYPOINT [ "pnpm", "svr", "dev" ]
